name: Keep Quotentator API Warm

on:
  schedule:
    - cron: "*/14 * * * *"
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping /randomQuote endpoint
        run: |
          echo "Pinging /randomQuote endpoint..."
          STATUS_CODE=$(curl -s -o /dev/null -w "%{http_code}" https://quotenatorapi.onrender.com/randomQuote)
          TIME_TOTAL=$(curl -s -o /dev/null -w "%{time_total}" https://quotenatorapi.onrender.com/randomQuote)
          echo "HTTP Status: $STATUS_CODE, Time: ${TIME_TOTAL}s"

          if [ "$STATUS_CODE" != "200" ]; then
            echo "/randomQuote failed with status $STATUS_CODE"
            exit 1
          fi
